apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-root-volume
  namespace: jenkins
  labels:
    type: aws-ebs-volume
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-23ddk32mda
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-volume-claim
  namespace: jenkins
  labels:
    type: aws-ebs-volume
spec:
  storageClassName: ""      
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: jenkins-root-volume

